language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - pypy

env:
  - DJANGO="django==1.8.4"
  - DJANGO="django==1.7.10"
  - DJANGO="django==1.4.22"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128,E125 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W userware; fi

matrix:
  exclude:
   - python: "3.4"
     env: DJANGO="django==1.4.22"
   - python: "3.3"
     env: DJANGO="django==1.4.22"
   - python: "2.6"
     env: DJANGO="django==1.7.10"
   - python: "2.6"
     env: DJANGO="django==1.8.4"

script: coverage run --source=userware manage.py test

after_success:
  coveralls

